spring:
  application:
    name: activityservice

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness_activity_db
      database: fitness_activity_db

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8083