server:
  port: 8084

spring:
  application:
    name: aiservice

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness_recommendations
      database: fitness_recommendations


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka